#!/usr/bin/env bun
/**
 * Generate the OTA image-signing keypair for THIS deployment. Run ONCE per fleet,
 * before building/flashing firmware:
 *
 *     bun infra/scripts/GenSigningKey.ts
 *
 * It writes:
 *   - infra/keys/ota_sign_priv.pem   the PRIVATE key — keep secret, gitignored,
 *                                    lives only on the build/publish host
 *   - infra/keys/ota_sign_pub.pem    the public key (convenience copy)
 *   - firmware/include/ota_pubkey.h  the public key embedded for the device —
 *                                    COMMIT this; devices verify OTA signatures against it
 *
 * PublishFirmware.ts signs each image with the private key; the device (performOta /
 * the /update flash) verifies against the embedded public key. See docs/HARDENING.md.
 *
 * The repo ships a placeholder ota_pubkey.h (the original author's public key). You
 * MUST run this to replace it with your own before deploying — otherwise you can't
 * sign updates (you don't hold the matching private key), and your fleet would trust
 * someone else's key.
 */
import { generateKeyPairSync } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";

const PRIV = "infra/keys/ota_sign_priv.pem";
const PUB = "infra/keys/ota_sign_pub.pem";
const HDR = "firmware/include/ota_pubkey.h";

// Refuse to clobber an existing private key: regenerating it would make every
// already-deployed device reject all future OTAs (they trust the OLD public key)
// until re-flashed over UART. Rotate deliberately, not by accident.
if (existsSync(PRIV)) {
  console.error(`${PRIV} already exists — refusing to overwrite.`);
  console.error(`Regenerating invalidates OTA for every deployed device until re-flashed.`);
  console.error(`To rotate on purpose: delete ${PRIV} first, then re-run (and UART-flash the new key — a compromised key can't sign the transition).`);
  process.exit(1);
}

mkdirSync("infra/keys", { recursive: true });
const { publicKey, privateKey } = generateKeyPairSync("rsa", {
  modulusLength: 2048,
  publicKeyEncoding: { type: "spki", format: "pem" },      // -----BEGIN PUBLIC KEY-----  (mbedtls_pk_parse_public_key)
  privateKeyEncoding: { type: "pkcs8", format: "pem" },    // node crypto.sign reads this in PublishFirmware.ts
});

writeFileSync(PRIV, privateKey, { mode: 0o600 });
writeFileSync(PUB, publicKey);

// Embed the public key as a C string, one PEM line per "..\n" — matches the format
// mbedtls_pk_parse_public_key(OTA_PUBKEY_PEM, sizeof(OTA_PUBKEY_PEM)) expects (NUL included).
const body = publicKey.trimEnd().split("\n").map((l) => `  "${l}\\n"`).join("\n");
writeFileSync(HDR,
`// OTA image-signing public key (RSA-2048). SAFE TO COMMIT — public half only.
// GENERATED by infra/scripts/GenSigningKey.ts — do not edit by hand.
// The matching private key lives in infra/keys/ (gitignored) on the build host.
#pragma once
static const char OTA_PUBKEY_PEM[] =
${body}
  ;
`);

console.log(`Signing keypair generated:`);
console.log(`  ${PRIV}   PRIVATE — secret, gitignored, build host only`);
console.log(`  ${HDR}    PUBLIC  — commit this; the device verifies against it`);
console.log(`Next: rebuild + flash firmware so the fleet trusts your key, then publish signed OTAs with PublishFirmware.ts.`);
